In [ ]:
import numpy as np
import pandas as pd
from sklearn import metrics
from sklearn import datasets
from numpy import array
from pandas import DataFrame
from pandas import concat
from keras.models import model_from_json
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import LabelEncoder

#Ruta del raiz de directorio.
Ruta="../"

In [34]:
#Datos La información sobre los trimetres de la estacion de la flora

FloraTotal_3mes = pd.read_excel(Ruta+'PreparacionDatos/FloraTotal_3mes_3V_mas_4.xlsx',sheet_name='FloraTotal', header=0)

FloraTotal_3mes

    Motos_vehiculos_particulares    Lluvia   Poblacion
0                     348066.000  0.939613  2244668.00
1                     348066.000  0.382813  2244668.00
2                     348066.000  0.263172  2244668.00
3                     348066.000  0.572834  2244668.00
4                     391327.000  0.190382  2269653.00
5                     391327.000  0.413592  2269653.00
6                     391327.000  0.408934  2269653.00
7                     391327.000  0.595508  2269653.00
8                     438769.000  0.060729  2294653.00
9                     438769.000  0.426957  2294653.00
10                    438769.000  0.107707  2294653.00
11                    438769.000  0.419806  2294653.00
12                    484119.000  0.185106  2319684.00
13                    484119.000  0.276111  2319684.00
14                    484119.000  0.134173  2319684.00
15                    484119.000  0.472869  2319684.00
16                    526339.000  0.215647  2344734.00
17                    526339.000  0.234257  2344734.00
18                    526339.000  0.281555  2344734.00
19                    526339.000  0.372491  2344734.00
20                    567353.000  0.208546  2369821.00
21                    567353.000  0.193502  2369821.00
22                    567353.000  0.110047  2369821.00
23                    567353.000  0.124192  2369821.00
24                    601794.000  0.265361  2394925.00
25                    601794.000  0.253803  2394925.00
26                    601794.000  0.088913  2394925.00
27                    601794.000  0.280813  2394925.00
28                    630478.000  0.015700  2420114.00
29                    630478.000  0.181820  2420114.00
30                    630478.000  0.148639  2420114.00
31                    630478.000  0.220213  2420114.00
32                   5989541.000  0.015700  2589521.98
33                   5390586.900  0.181820  2589521.98
34                   4581998.865  0.148639  2589521.98
35                   3665599.092  0.220213  2589521.98

In [38]:
#Cargo el modelo antes generado.
json_file = open('../Modelamiento/model.json', 'r')
loaded_model_json = json_file.read()
json_file.close()
loaded_model = model_from_json(loaded_model_json)
# Cargo el nuevo modelo
loaded_model.load_weights("../Modelamiento/LTSM_Cali_3meses.h5")
loaded_model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
lstm_3 (LSTM)                (None, 50)                10800
_________________________________________________________________
dense_3 (Dense)              (None, 1)                 51
=================================================================
Total params: 10,851
Trainable params: 10,851
Non-trainable params: 0
_________________________________________________________________

In [43]:
values = FloraTotal_3mes.values

In [44]:
values = values.reshape((values.shape[0], 1, values.shape[1]))

In [46]:
values.shape

(36, 1, 3)

In [47]:
yhat = loaded_model.predict(values, verbose=0)
print(yhat)

[[1.0459689]
 [1.0459689]
 [1.0459689]
 [1.0459689]
 [1.0459689]
 [1.0459689]
 [1.0459689]
 [1.0459689]
 [1.0459689]
 [1.0459689]
 [1.0459689]
 [1.0459689]
 [1.6356308]
 [1.6356308]
 [1.6356308]
 [1.6356308]
 [1.7393099]
 [1.7393099]
 [1.7393099]
 [1.7393099]
 [1.7393099]
 [1.7393099]
 [1.7393099]
 [1.7393099]
 [1.7393099]
 [1.7393099]
 [1.7393099]
 [1.7393099]
 [1.7393099]
 [1.7393099]
 [1.7393099]
 [1.7393099]
 [3.508834 ]
 [3.508834 ]
 [3.508834 ]
 [3.2241385]]

In [ ]:
df = pd.DataFrame({ 'Motos_vehiculos_particulares':    [348066,348066],
                    'Lluvia': [148.0,939612567424774,148.0,382813453674316],
                    'Poblacion': [2244668,2244668]

                   })

In [ ]:
values = df.values
values = values.reshape((values.shape[0], 1, values.shape[1]))
yhat = loaded_model.predict(values, verbose=0)
print(yhat)